### ISSUE TITLE
[Specific to branch feature/SupportAndroid13] Android 13 does not display Splashscreens

### ISSUE THREAD

**Issue by nguyeenvy** [nventive/UnoApplicationTemplate#315] opened 2023-05-17 15:08 UTC
## Expected Behavior
Upon opening the application, the splashscreens should display correctly.

## Actual Behavior
Upon opening the application, the splashscreens are not displayed correctly.

## Steps to Reproduce the Problem

1. Build the application and deploy it on an Android device or emulator.
2. Open the app.
3. Look at the welcome and log in pages.

## Specifications

- Version: Android 13
- Platform: Android devices
- Subsystem:

## Image
![MicrosoftTeams-image](https://github.com/nventive/UnoApplicationTemplate/assets/54756963/b454ec29-c8b0-4af8-a2df-ab54cffae102)

## Link of branch
https://github.com/nventive/UnoApplicationTemplate/tree/dev/vyng/Support-Android-13

**Comment by Soap-141** [comment] 2023-05-17 15:11
Do you have any video or GIF file?

**Comment by nguyeenvy** [comment] 2023-05-17 15:12
> Do you have any video or GIF file?

@Soap-141 No but I have a picture.

**Comment by nguyeenvy** [comment] 2023-05-17 15:22
@Soap-141 A picture was added in the description above.

**Comment by nguyeenvy** [comment] 2023-05-17 15:35
@Soap-141 To me, the app worked fine, it was just every splashscreen that was not displayed correctly.

**Comment by Soap-141** [comment] 2023-05-17 15:43
Is it only on the first installation?

**Comment by nguyeenvy** [comment] 2023-05-17 15:46
@Soap-141 What do you mean? I can also retest it one more time with the application uninstalled and with git clean -fdx. I can get back to you.

**Comment by jeanplevesque** [comment] 2023-05-17 15:47
@nguyeenvy Add a link to the branch that reproduces this issue. 😀

**Comment by Soap-141** [comment] 2023-05-17 15:56
> @Soap-141 What do you mean? I can also retest it one more time with the application uninstalled and with git clean -fdx. I can get back to you.

Meant that if you restart the application does it happen again?

**Comment by nguyeenvy** [comment] 2023-05-17 16:20
@Soap-141 So I just deleted the app from my device and I redeployed it, and I did not get the issue. When I restart the application, I also don't have the issue anymore.

**Comment by Soap-141** [comment] 2023-05-17 16:21
@nguyeenvy @jeanplevesque Looks like a .NET 6+ issue. Happens to me sometime every assets in like random and misplaced. Closing the issue for now.

**Closed by Soap-141** 2023-05-17 16:21 UTC
